### ISSUE TITLE
How to organize the naming convention guides according to different models/approaches.

### ISSUE THREAD

**Issue by cesiztel** [naming-convention/naming-convention-guides#3]
Hi guys, 

I was thinking to contribute to the Git naming conventions. In the majority of my projects I've use this model (https://nvie.com/posts/a-successful-git-branching-model/) . This branching model encourage certain naming conventions. I am aware that every developer in the community reshapes this model to his own workflow and needs. But I think worth to described the guideline as it was described in first place. 

For me this is not a standard, it is just a well know naming convention guideline and I am not sure what is the best way to organice this in the guideline. 

If you guys want to integrate cases like this, I would say to add  one section to the main Git section with the name `Known models` or `Common cases`  where we can explain in there which naming conventions this case encourage (keeping the same format as the main README).

What do you think?

**Comment by farbodsaraf** [comment]
Hi César, Thanks a lot for your question. Actually it's one of the biggest challenges that we're facing. There are many models and tastes out there and our goal for the moment is to keep it as general as possible and only list the naming conventions which are widely accepted and being used by all developers. That might come with a cost, for instance we might loose an opportunity to list something which is better than the current generally accepted naming convention, however, in order to not overwhelmed the visitors with tons of different types of information and models, we would like to keep it limited to just one taste/model per topic and technology.

This might change in the future, once we find a better way of representing different models and tastes in each section. For instance, we're planning to change Gitbook template to allow nested section under sub-section and in those case we could add the other models as sub-section.

For now, since we're sticking to the very general accepted approach, is there any thing which you can add from the model above to our current git naming conventions as an improvement?

**Comment by cesiztel** [comment]
Hi @farbodsaraf , thanks a lot for answering. :smiley:

Yes, I think I have an improvement. If we are using `Feature git flow` and `Gitflow` we can suggest to encourage the following branching naming conventions:

### Branches

- Branch `develop`: current development branch
- Branch `master`: production code
- Branches with prefix `feature`: branches that only include new features
- Branches with prefix `hotfix`: branches checkout from `master` and only include production fixes
Usual conventions for hotfix branches: `hotfix/{new-deploy-version}`

### Tags

If we use [Semantic versioning](https://semver.org/) and gitflow, may encouraged use the version number for the tag:
``` git tag -a {X.Y.Z} ``` or ``` git tag -a v{X.Y.Z} ```

### Commits

For commit messages I would like to suggest the conventions of [Convetional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.3/)

Makes sense? :no_mouth:

**Comment by farbodsaraf** [comment]
Hi @cesiztel, many thank again for your suggestions.

Regarding your **branch** suggestions, you can add all except the usual convention for hotfix branches cause our own suggested branching format which I listed below covers that as well, doesn't it?
{work type e.g.}/{2-3 word summary}/{story or ticket id}

The Tags section is missing so please feel free to add **Tags** to the git part.

Regarding commits, the format looks good, but you need to merge the conventional commits format with what we already have to make a very comprehensive one. Would that be possible?

Let me know your thoughts. Thanks.

**Comment by cesiztel** [comment]
Hi @farbodsaraf , 

I am preparing the PR for the tagging and another one for the commits. I think is possible add Conventional commits to it. 

Thanks. I will close this issue and we can discuss over the PR's
